sudo: false
language: ruby
cache:
  - bundler
install: true # skip bundle install
notifications:
  email: false

matrix:
  include:
    - env: TRAVIS_JOB=test
      rvm: 2.5.6

script: bash ./script/travis.sh
